version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travellist

    node:
        image: node:10-alpine
        container_name: travellist-node
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
            - ./docker-compose/node/:/init-scripts/
        entrypoint:
            - /init-scripts/node_start.sh
        depends_on:
            - app
        command: >
            CMD ["tail", "-f", "/dev/null"]

    db:
        image: mysql:5.7
        container_name: travellist-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - travellist

    nginx:
        image: nginx:1.17-alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8018:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - travellist

networks:
  travellist:
    driver: bridge